config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'static#index'
  get '/about' => 'static#about'
  get '/contact' => 'static#contact'

  # User auth/sessions
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'
  get '/register' => 'users#new'
  match '/auth/:provider/callback', to: 'sessions#omni', via: %i[get post], as: 'omni'

  # Dashboard
  get '/users/dashboard' => 'users#dashboard'

  # Search
  get '/search' => 'search#index', as: 'search'
  get '/search?q=params[:query]' => 'search#results'

  resources :posts, only: %i[index create]

  namespace :private do
    resources :conversations
  end

  resources :users do
    get '/follow' => 'users#follow'
    get '/unfollow' => 'users#unfollow'
    resources :posts, except: %i[edit update]
  end

  resources :communities do
    get '/join' => 'communities#join'
    get '/leave' => 'communities#leave'
    get '/member-permissions' => 'communities#permissions'
    resources :posts, except: %i[edit update]
    resources :memberships, only: %i[edit update]
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_secure_password
  enum role: { user: 0, moderator: 1, admin: 2 }

  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :echoes, foreign_key: 'echoer_id'

  has_many :communities, foreign_key: 'admin_id'
  has_many :community_memberships
  has_many :memberships, through: :community_memberships, source: :community

  has_many :received_follows, class_name: 'Follow', foreign_key: 'following_id', dependent: :destroy
  has_many :followers, through: :received_follows, source: :follower

  has_many :follows_given, class_name: 'Follow', foreign_key: 'follower_id', dependent: :destroy
  has_many :following, through: :follows_given, source: :following

  has_many :participants, class_name: 'Private::Participant'
  has_many :conversations, through: :participants, class_name: 'Private::Conversation'
  has_many :messages, class_name: 'Private::Message'

  has_one_attached :avatar
  has_one_attached :header_image

  validates :username, uniqueness: true, presence: true, length: { minimum: 3, maximum: 14 }, format: { with: /\A[\w-]+\z/,
                                                                                                        message: "Invalid username. Please choose another!" }
  validates :email, uniqueness: true, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :password, length: { in: 8..50 }
  validates :bio, length: { maximum: 200, too_long: "Bio cannot exceed %{count} characters."}

  def first_name
    self.name.split(' ')[0]
  end

  private

  def self.create_with_omniauth(auth)
    create! do |user|
      username = auth['info']['name'].to_s.split
      username = username[0] + rand(100..1000).to_s

      user.provider = auth['provider']
      user.uid = auth['uid']
      user.username = username
      user.email = auth['info']['email']
      user.password = auth["uid"] + username
      if auth['info']
         user.name = auth['info']['name'] || ""
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include ApplicationHelper
  include UsersHelper
  before_action :set_user, only: [:show, :edit, :update, :destroy, :follow, :unfollow]
  load_and_authorize_resource param_method: :user_params

  def index
    @users = User.all.paginate(page: params[:page], per_page: 30)
  end

  def show; end

  def dashboard; end

  def edit; authorize! :edit, @user end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = 'User was successfully updated'
      redirect_to @user
    else
      flash[:error] = 'Something went wrong'
      render 'edit'
    end
    authorize! :update, @user
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = 'Use successfully created'
      session[:user_id] = @user.id
      redirect_to root_path
    else
      flash.now[:danger] = 'Something went wrong. Please try again.'

      render new_user_path
    end
    authorize! :create, @user
  end

  def destroy
    authorize! :destroy, User.find(params[:id])
    if destroy_user_data(params[:id], what: 'all')
      flash[:success] = 'Your account, shops, and invites were successfully deleted.'
      redirect_to root_path
    else
      flash[:error] = 'Something went wrong'
      redirect_to users_url
    end
  end

  def follow 
    @follow = current_user.follows_given.new(following_id: params[:user_id])
    if @follow.save
      flash[:success] = "You are now following #{@user.username}"
      redirect_to user_path(@user)
    else
      flash[:danger] = 'Something went wrong. Please try again.'
      redirect_to user_path(@user)
    end
  end

  def unfollow 
    @follow = current_user.follows_given.find_by(following_id: params[:user_id])
    if @follow.destroy
      flash[:success] = "You have unfollowed #{@user.username}."
      redirect_to user_path(@user)
    else
      flash[:danger] = 'Something went wrong. Please try again.'
      redirect_to user_path(@user)
    end
  end

  private

  def set_user
    if params[:user_id]
      @user = User.find(params[:user_id]) 
    else
      @user = User.find(params[:id]) 
    end
  end

  def user_params
    params.require(:user).permit(:username, :name, :email, :password, :password_confirmation, :bio, :twitter_url, :facebook_url, :website_url, :avatar, :header_image)
  end
end

app/helpers/users_helper.rb
module UsersHelper

  def is_following?(user)
    follow = current_user.follows_given.find_by(following_id: user.id)
    follow.presence ? true : false
  end

  def is_admin?(user)
    user.role == "admin"
  end

  def dashboard_activity_posts(user)
    activity = []

    # Searching through users.
    user.following.each do |following|
      activity.concat(following.posts)  
    end

    # 
    user.communities.each do |community|
      community.posts.each do |commpost|
        activity.concat(comm.posts) unless commpost.user_id == user.id
      end
    end  

    activity = activity.sort_by{|e| e[:created_at]}.reverse
  end

  private

end

app/views/users/_edit_form.erb
<div class="row">
  <h2>Edit Profile</h2>
</div>

<%= form_with model: @user, local: true do |f| %>
  <div class="form-row mt-4">
    <div class="form-group col-xl-3 mx-auto text-center">
      <% if @user.avatar.presence %>
        <%= image_tag @user.avatar.variant(resize_to_limit: [200, 200]), class: "mb-3 mx-auto" %>
      <% end %>
      <div class="row mx-auto">
        <%= label_tag :avatar, "Avatar", class: "mt-4 mx-auto" %>
        <%= f.file_field :avatar, class: "form-control-file mx-auto mb-4" %>
      </div>
      <% if @user.header_image.presence %>
        <%= image_tag @user.header_image.variant(resize_to_limit: [200, 200]), class: "mb-3 mx-auto" %>
      <% end %>
        <div class="row mx-auto">
          <%= label_tag :header_image, "Header Image", class: "mt-4 mx-auto" %>
          <%= f.file_field :header_image, class: "form-control-file mx-auto mb-4" %>
        </div>
    </div>
  
      
  <div class="col-xl-9">
    <div class="form-row">
      <div class="form-group col-xl-6">
        <%= label_tag :name, "Name" %> 
        <%= f.text_field :name, class: "form-control form-control-lg" %>
      </div>

      <div class="form-group col-xl-6">
        <%= label_tag :username, "Username" %> 
        <%= f.text_field :username, class: "form-control form-control-lg" %>
      </div>

      <div class="form-group col-xl-6">
        <%= label_tag :password, "Password" %> 
        <%= f.password_field :password, class: "form-control form-control-lg" %>
      </div>

      <div class="form-group col-xl-6">
        <%= label_tag :password_confirmation, "Confirm Password" %> 
        <%= f.password_field :password_confirmation, class: "form-control form-control-lg" %>
      </div>
          
      <div class="form-group col-xl-6">
        <%= label_tag :email, "E-mail Address" %> 
        <%= f.text_field :email, class: "form-control form-control-lg" %>
      </div>

      <div class="form-group col-xl-6">
        <%= label_tag :facebook, "Facebook URL" %> 
        <%= f.text_field :facebook_url, class: "form-control form-control-lg" %>
      </div>
      
      <div class="form-group col-xl-6">
        <%= label_tag :twitter_url, "Twitter URL" %>
        <%= f.text_field :twitter_url, class: "form-control form-control-lg" %>
      </div>  

      <div class="form-group col-xl-6">
        <%= label_tag :website_url, "Website Address" %> 
        <%= f.text_field :website_url, class: "form-control form-control-lg" %>
      </div> 
    </div>

    <div class="form-row">
      <div class="form-group col-xl-12">
        <%= label_tag :bio, "Bio" %>
        <%= f.text_area :bio, class: "form-control form-control-lg", rows: "6"%>
      </div>  
    </div>

    <div class="form-row float-right">
      <%= f.submit "Submit", :class => "btn btn-primary" %>
      <% if current_user %>
        <%= f.submit "Delete Account", :class => "btn btn-danger mx-2", data: { confirm: 'Are you sure? This will delete your account and ALL associated data!' } %>
      <% end %>
    </div>  

    </div>
<% end %>

app/views/users/_user_card.erb
  
<div class="col-xl-4">
  <!-- Card -->
  <div class="card card-cascade wider reverse">
    <!-- Card image -->
    <div class="view view-cascade overlay">
      <% if user.header_image.presence %>
        <%= image_tag user.header_image, class: "card-img-top header-image" %>
      <% else %>
        <img class="card-img-top" src="https://mdbootstrap.com/img/Photos/Slides/img%20(70).jpg" alt="Card image cap">
      <% end %>
      <a href="#!">
        <div class="mask rgba-white-slight"></div>
      </a>
    </div>
    <div class="card-avatar mx-auto d-block">
      <% if user.avatar.presence %>
        <%= image_tag user.avatar.variant(resize_to_limit: [120, 120]), class: "rounded-circle" %>
      <% else %>
        <img class="card-img-100 d-flex" src="https://mdbootstrap.com/img/Photos/Avatars/img%20(8).jpg" alt="Generic placeholder image">
      <% end %>
    </div>
    
    <!-- Card content -->
    <div class="card-body card-body-cascade text-center pt-1">
      <!-- Title -->
      <h4 class="card-title mb-0">
        <strong>@<%= user.username %></strong>
      </h4>
      <% if is_admin?(user) %>
          <span class="badge badge-pill badge-success mt-0 mb-2 z-depth-0">Admin</span>
      <% end %>
      <!-- Subtitle -->
      
      <!-- Text -->
      <p class="card-text">
        <%= user.bio %>
      </p>
      <% if current_user %>
        <% if is_following?(user) %>
          <p><%= link_to "Unfollow", user_unfollow_path(user), class: "btn btn-danger btn-sm btn-block" %></p>
        <% elsif current_user.id == user.id %>
          
        <% else%>
          <p><%= link_to "Follow", user_follow_path(user), class: "btn btn-primary btn-sm btn-block" %></p>
        <% end %>
      <% end %>
        
        <% if user.facebook_url != "" %>
          <a class="btn btn-info btn-rounded z-depth-0" href="<%= user.facebook_url %>"><i class="fab fa-facebook-f"></i></a>
        <% end %>
        <% if user.twitter_url != "" %>
          <a class="btn btn-info btn-sm btn-rounded z-depth-0" href="<%= user.twitter_url %>"><i class="fab fa-twitter"></i> Twitter</a>
        <% end %>
        <% if user.website_url != "" %>
          <a class="btn btn-info btn-sm btn-rounded z-depth-0" href="<%= user.website_url %>"><i class="fas fa-globe-americas"></i> Website</a>
        <% end %>
      
    </div>
  </div>
  <!-- Card -->
  <!-- Card -->
  <div class="row">
  <div class="col-xl-12 col-sm-4">
    <div class="card card-cascade wider mt-3">
      <!-- Card image -->
      <div class="view view-cascade gradient-card-header peach-gradient">
        <!-- Title -->
        <h2 class="card-header-title my-4 white-text mx-auto text-center"><strong><%= number_to_human(user.followers.count) %></strong> <small class="mb-0">Followers</small></h2>
        <!-- Text -->
      </div>
    </div>
  </div>
  <!-- Card -->
  <!-- Card -->
  <div class="col-xl-12 col-sm-4">
    <div class="card card-cascade wider mt-3">
      <!-- Card image -->
      <div class="view view-cascade gradient-card-header aqua-gradient">
        <!-- Title -->
        <h2 class="card-header-title my-4 white-text mx-auto text-center"><strong><%= number_to_human(user.following.count) %></strong> <small class="mb-0">Following</small></h2>
        <!-- Text -->
      </div>
    </div>
  </div>


    <div class="col-xl-12 col-sm-4">
      <div class="card card-cascade wider mt-3">
        <!-- Card image -->
        <div class="view view-cascade gradient-card-header purple-gradient">
          <!-- Title -->
          <h2 class="card-header-title my-4 white-text mx-auto text-center"><strong><%= number_to_human(user.community_memberships.count) %></strong> <small class="mb-0"> Memberships</small></h2>
          <!-- Text -->
        </div>
      </div>
    </div>
    </div>
</div>

app/views/users/dashboard.erb
<div class="container-lg container-body py-5 px-4">
  <div class="card-group">
    <%= render partial: "users/user_card", locals: {user: current_user} %>
    <div class="col-xl-8">
      <section class="my-4">
        <h2>Welcome back, <%= current_user.first_name %>! </h2>
        <h4>Here's what your friends are up to...</h4>
        <%= render partial: "posts/post_block", locals: {post: dashboard_activity_posts(current_user)} %>
        <h4>Check out the most commented posts...</h4>
        <%= render partial: "posts/post_block", locals: {post: Post.most_commented} %>
      </section>
    </div>
  </div>
</div>

app/views/users/edit.erb
<div class="container-lg container-body py-5 px-4">
  <%= render "edit_form" %>
</div>

app/views/users/index.erb
<div class="container-lg container-body py-5 px-4">
  <div class="card-group">
    <%= render partial: "users/user_card", locals: {user: current_user} %>
      <div class="col-xl-8">
        <section class="my-4">
          <% if current_user %>
            <h2>Users</h2>
            <table class="table">
              <thead class="black white-text">
                <tr>
                  <th>Username</th>
                  <th>Name</th>
                  <th>E-mail</th>
                  <th class="text-center">Actions</th>
                </tr>
              </thead>

              <tbody>
                <% @users.each do |user| %>
                  <tr>
                    <td><%= link_to user.username, user_path(user) %></td>
                    <td><%= link_to user.name, user_path(user) %></td>
                    <td><%= user.email %></td>
                    <td class="text-center">
                      <%= link_to 'View', user %> 
                      <% if is_admin?(current_user) %>
                        | <%= link_to 'Edit', edit_user_path(user) %> | 
                        <%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %>
                      <% end %>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
            <div class="row float-right">
              <%= will_paginate @users %>
            </div>
          <% end %>
        </section>
      </div>
    </div>
  </div>
</div>

app/views/users/new.erb
<div class="container-lg container-body py-5 px-4">
    <%= render partial: "edit_form" %>
   
</div>

app/views/users/show.erb
<div class="container-lg container-body py-5 px-4">
  <div class="card-group">
    <%= render partial: "users/user_card", locals: {user: @user} %>
    <div class="col-xl-8">
      <section class="my-4">
        <!-- Card header -->
        <div class="card-header border-0 font-weight-bold d-flex justify-content-between"> 
          <ul class="nav nav-tabs" id="myTab" role="tablist">
            <li class="nav-item pr-2">
              <a class="active" id="activity-tab" data-toggle="tab" href="#activity" role="tab" aria-controls="activity"
            aria-selected="true">Activity</a> 
            </li>
            |
            <li class="nav-item pl-2">
            <a id="replies-tab" data-toggle="tab" href="#replies" role="tab" aria-controls="replies"
            aria-selected="false">Replies</a>
            </li>
            </ul>

          <ul class="list-unstyled list-inline mb-0">
            <li class="list-inline-item"><a href="" class="mr-3"><i class="fas fa-envelope mr-1"></i>Send message</a></li>
              <% if current_user && is_following?(@user) %>
                <li class="list-inline-item">
                  <%= link_to user_unfollow_path(@user) do %>
                    <i class="fas fa-at mr-1"></i>Unfollow
                  <% end %>
                </li>
              <% elsif current_user && current_user.id == @user.id %>
              <% else %>
                <li class="list-inline-item">
                  <%= link_to user_follow_path(@user) do %>
                    <i class="fas fa-at mr-1"></i>Follow
                  <% end %>
                </li>
              <% end %>
          </ul>
        </div>
        <div class="tab-content" id="myTabContent">
          <div class="tab-pane fade show active" id="activity">
            <%= render partial: "posts/post_block", locals: {post: @user.posts.where(parent_id: nil).order(created_at: :desc).paginate(page: params[:page], per_page: 10)} %>
          </div>
          <div class="tab-pane fade" id="replies" role="tabpanel" aria-labelledby="replies-tab">
            <%= render partial: "posts/replies_tab", locals: {post: @user.posts.order(created_at: :desc).paginate(page: params[:page], per_page: 10)} %>
          </div>
        </div>
      </section>
    </div>
  </div>
</div>