config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'static#index'
  get '/about' => 'static#about'
  get '/contact' => 'static#contact'

  # User auth/sessions
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'
  get '/register' => 'users#new'
  match '/auth/:provider/callback', to: 'sessions#omni', via: %i[get post], as: 'omni'

  # Dashboard
  get '/users/dashboard' => 'users#dashboard'

  # Search
  get '/search' => 'search#index', as: 'search'
  get '/search?q=params[:query]' => 'search#results'

  resources :posts, only: %i[index create]

  namespace :private do
    resources :conversations
  end

  resources :users do
    get '/follow' => 'users#follow'
    get '/unfollow' => 'users#unfollow'
    resources :posts, except: %i[edit update]
  end

  resources :communities do
    get '/join' => 'communities#join'
    get '/leave' => 'communities#leave'
    get '/member-permissions' => 'communities#permissions'
    resources :posts, except: %i[edit update]
    resources :memberships, only: %i[edit update]
  end
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  self.per_page = 10

  belongs_to :user
  belongs_to :community, optional: true
  belongs_to :parent, class_name: 'Post', optional: true

  has_many :likes, dependent: :destroy
  has_many :replies, class_name: 'Post', foreign_key: 'parent_id'
  has_many :echoes, foreign_key: 'source_post_id'

  validates_presence_of :body

  has_many_attached :images

  before_save :convert_to_markdown

  scope :today, -> { where('created_at >= ?', Time.now - 1.day) }

  def self.most_commented
    mc = Post.where('parent_id > 0').group("parent_id").count
    posts = []
    mc.each do |post, cc|
      posts << Post.find(post)
    end
    posts
  end

  private

  def convert_to_markdown
    markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML,
                                       autolink: true,
                                       space_after_headers: true,
                                       superscript: true,
                                       highlight: true,
                                       footnotes: true)

    self.parsed_body = markdown.render(body)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all.paginate(page: params[:page], per_page: 30)
  end

  # GET /posts/1
  def show; end

  # GET /posts/new
  def new
    @post = Post.new(params[:id])
  end

  # GET /posts/1/edit
  def edit; end

  # POST /posts
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        if @post.parent
          format.html { redirect_to user_post_path(@post.parent.user, @post.parent), success: 'Post was successfully created.' }
        end
        format.html { redirect_to user_post_path(@post.user, @post), success: 'Post was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /posts/1
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /posts/1
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to user_path(@post.user), notice: 'Post was successfully destroyed.' }
    end
  end

private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:body, :user_id, :community_id, :parent_id)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_new_post_modal.erb
<div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel"
  aria-hidden="true" id="modalPostForm">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header text-center">
        <h4 class="modal-title w-100 font-weight-bold">New Post</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <%= form_with model: Post.new do |f| %>
        <%= f.hidden_field :parent_id %>
        <%= f.hidden_field :user_id, value: current_user.id %>
        <div class="modal-body mx-3">
            <%= f.collection_select(:community_id, current_user.communities, :id, :name, {:prompt => 'Post Globally (or Select Community)'}, class: "browser-default custom-select custom-select-lg mb-3 z-depth-1") %>
          <div class="form-group shadow-textarea">
            <h5>Body</h5>
            <%= f.text_area :body, class: "form-control z-depth-1", id: "exampleFormControlTextarea345", rows: "10", style: "padding-left: 1rem; padding-top: 1rem;" %>
            <%= label_tag :body, "Content", class: "sr-only" %>
          </div>
        </div>
        <div class="modal-footer d-flex justify-content-center">
          <%= f.submit "Submit", :class => "btn btn-green" %>
        </div>
      </div>
    <% end %>
    </div>
  </div>
</div>

app/views/posts/_new_reply_modal.erb
<div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel"
  aria-hidden="true" id="modalPostForm">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header text-center">
        <h4 class="modal-title w-100 font-weight-bold">Reply to Post</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <%= form_with model: Post.new do |f| %>
        <%= f.hidden_field :parent_id %>
        <%= f.hidden_field :user_id, value: current_user.id %>
        <div class="modal-body mx-3">
          <div class="form-group shadow-textarea">
            <h5>Body</h5>
            <%= f.text_area :body, class: "form-control z-depth-1", id: "exampleFormControlTextarea345", rows: "10", style: "padding-left: 1rem; padding-top: 1rem;" %>
            <%= label_tag :body, "Content", class: "sr-only" %>
          </div>
        </div>
        <div class="modal-footer d-flex justify-content-center">
          <%= f.submit "Submit", :class => "btn btn-green" %>
        </div>
      </div>
    <% end %>
    </div>
  </div>
</div>

app/views/posts/_post_block.erb
<% post.each do |post| %>
  <div class="media mt-4 mb-3 px-1 text-md-left border-1">
    <div class="media-body ml-2 mt-1" style="width: 100%;">
    <% if post.user.avatar.presence %>
      <%= image_tag post.user.avatar.variant(resize_to_limit: [60, 60]), class: "card-img-60 d-flex rounded-circle mr-2 float-left" %>
    <% else %>
      <img class="card-img-40 d-flex mr-2 float-left" src="https://mdbootstrap.com/img/Photos/Avatars/img%20(8).jpg" alt="Generic placeholder image" height="40" width="40">
    <% end %>
      <h5 class="font-weight-bold mt-0 mb-0 text-muted float-left">
        <%= link_to post.user.name, user_path(post.user) %>
      </h5><br>
      <small class="text-muted d-block mb-3">@<%= link_to post.user.username, user_path(post.user) %></small>
        <p style="ml-3">
        <% if post.body.length > 600 %>
          <%= sanitize(post.parsed_body.truncate(600), tags: %w(h3 h2 p)) %>
          <%= link_to "Read full post", user_post_path(post.user, post) %>
        <% else %>
          <%= raw(post.parsed_body) %>
        <% end %>
        </p>
        <% if post.parent_id %>
          <div class="media mt-4 mb-2 px-2 pt-2 text-md-left border-1" style="background: #f9f9f9">
            <div class="media-body">
              <h6 class="mt-0 mb-0 text-muted">
                Reply to @<%= link_to post.parent.user.username, user_post_path(post.parent.user, post.parent) %>
              </h6>
              <p class="mt-2"><%= sanitize(post.parent.parsed_body.truncate(300)) %></p>
            </div>
          </div>
        <% end %>

      <div class="row" style="background: #f9f9f9; padding-top: 5px; padding-bottom: 5px; margin-left: 1px; margin-right: 1px;">
        <small class="blue-grey-text pl-3">
          <%= post.created_at.strftime("%B %e at %H:%M") %>
          <% if post.parent_id %>
            as reply to <%= link_to post.parent.user.username, user_post_path(post.parent.user, post.parent) %>
          <% elsif post.community %>
            in <%= link_to post.community.name, community_path(post.community) %>
          <% else %>
            in Global 
          <% end %>
          <% if post.community %>
            <a href="#modalPostForm" class="pl-3" data-toggle="modal" data-id="<%= post.id %>" data-community="<%= post.community.id %>"><i class="fas fa-comment-dots"></i> Reply</a>
          <% else %>
            <a href="#modalPostForm" class="pl-3" data-toggle="modal" data-id="<%= post.id %>"><i class="fas fa-comment-dots"></i> Reply</a>
          <% end %>
          <a class="pl-3"><i class="fas fa-quote-right"></i> Repost</a>
            <%= link_to user_post_path(post.user, post), class: "pl-2" do %>
              View Post (<%= pluralize(post.replies.count, 'reply') %>)  
            <% end %>   
            <% if current_user %>
            <% if post.user.id == current_user.id %>
              <%= link_to user_post_path(post.user, post), method: "delete", class: "pl-2", data: { confirm: 'Are you sure you want to delete this post?' } do %>
                <i class="fas fa-trash-alt"></i>
              <% end %>
            <% end %>
          <% end %>
        </small>
      </div>
    </div>
  </div>
<% end %>

app/views/posts/_replies_tab.erb
 <% post.where.not(parent_id: nil).each do |post| %>
  <div class="media mt-4 mb-3 px-1 text-md-left border-1" >
    <% if post.user.avatar.presence %>
      <%= image_tag post.user.avatar.variant(resize_to_limit: [80, 80]), class: "card-img-80 d-flex rounded-circle mr-3" %>
    <% else %>
      <img class="card-img-100 d-flex z-depth-1 mr-3" src="https://mdbootstrap.com/img/Photos/Avatars/img%20(8).jpg" alt="Generic placeholder image">
    <% end %>
    <div class="media-body ml-2 mt-1" style="width: 100%;">
      <h5 class="font-weight-bold mt-0 mb-0 text-muted">
        <%= link_to post.user.name, user_path(post.user) %><small class="text-muted align-middle pl-2">@<%= link_to post.user.username, user_path(post.user) %></small>
      </h5>
      <p class="mt-2">
      <%= raw(post.parsed_body) %>
      </p>
              <div class="media mt-4 mb-2 px-2 pt-2 text-md-left border-1" style="background: #f9f9f9">
                  <div class="media-body">
                    <h6 class="mt-0 mb-0 text-muted">
                      Reply to @<%= link_to post.parent.user.username, user_post_path(post.parent.user, post.parent) %>
                    </h6>
                    <p class="mt-2"><%= sanitize(post.parent.parsed_body.truncate(300)) %></p>
                  </div>
                </div>
      </p>
      <div class="row" style="background: #f9f9f9; padding-top: 5px; padding-bottom: 5px; margin-left: 1px; margin-right: 1px;">
        <small class="blue-grey-text pl-3">
          Posted <%= post.created_at.strftime("%B %e at %H:%M") %>
          <% if post.parent_id %>
            as reply to <%= link_to post.parent.user.username, user_post_path(post.parent.user, post.parent) %>
          <% elsif post.community %>
            in <%= link_to post.community.name, community_path(post.community) %>
          <% else %>
            in Global 
          <% end %>
          <% if post.community %>
            <a href="#modalPostForm" class="pl-3" data-toggle="modal" data-id="<%= post.id %>" data-community="<%= post.community.id %>"><i class="fas fa-comment-dots"></i> Reply</a>
          <% else %>
            <a href="#modalPostForm" class="pl-3" data-toggle="modal" data-id="<%= post.id %>"><i class="fas fa-comment-dots"></i> Reply</a>
          <% end %>
          <a class="pl-3"><i class="fas fa-quote-right"></i> Repost</a>
            <%= link_to user_post_path(post.user, post), class: "pl-2" do %>
              View Post (<%= pluralize(post.replies.count, 'reply') %>)  
            <% end %>         
            <% if current_user %>
            <% if post.user.id == current_user.id %>
              <%= link_to user_post_path(post.user, post), method: "delete", class: "pl-2", data: { confirm: 'Are you sure you want to delete this post?' } do %>
                <i class="fas fa-trash-alt"></i>
              <% end %>
            <% end %>
          <% end %>
        </small>
      </div>
    </div>
  </div>
<% end %>

app/views/posts/_reply_block.erb
<% post.each do |post| %>
  <div class="media mt-4 mb-3 px-1  text-md-left border-1">
    <% if post.user.avatar.presence %>
      <%= image_tag post.user.avatar.variant(resize_to_limit: [80, 80]), class: "card-img-80 d-flex rounded-circle mr-3" %>
    <% else %>
      <img class="card-img-80 d-flex z-depth-1 mr-3" src="https://mdbootstrap.com/img/Photos/Avatars/img%20(8).jpg" alt="Generic placeholder image">
    <% end %>
    <div class="media-body ml-2 mt-1">
      <h5 class="font-weight-bold mt-0 mb-0 text-muted">
        <%= link_to post.user.name, user_path(post.user) %><small class="text-muted align-middle pl-2">@<%= link_to post.user.username, user_path(post.user) %></small>
      </h5>
      <p class="mt-2">
        <%= raw(post.parsed_body) %>
      </p>

      <% if post.parent_id and post.parent_id.to_s != params[:id] %>
        <div class="media mt-4 mb-4 px-2 pt-2 text-md-left border-1" style="background: #f9f9f9">
          <% if post.parent.user.avatar.presence %>
              <%= image_tag post.parent.user.avatar.variant(resize_to_limit: [80, 80]), class: "card-img-80 d-flex rounded-circle mr-3" %>
            <% else %>
              <img class="card-img-100 d-flex z-depth-1 mr-3" src="https://mdbootstrap.com/img/Photos/Avatars/img%20(8).jpg" alt="Generic placeholder image">
            <% end %>
            <div class="media-body">
              <h5 class="font-weight-bold mt-0 mb-0 text-muted">
                <%= link_to post.parent.user.name, user_post_path(post.parent.user, post.parent) %><small class="text-muted align-middle pl-2">@<%= link_to post.parent.user.username, user_post_path(post.parent.user, post.parent) %></small>
              </h5>
              <p class="mt-2"><%= sanitize(post.parent.parsed_body.truncate(300)) %></p>
            </div>
          </div>
          
          
        <% end %>

      <div class="row" style="background: #f9f9f9; padding-top: 5px; padding-bottom: 5px; margin-left: 1px; margin-right: 1px;">
        <small class="blue-grey-text pl-3">
          Posted <%= post.created_at.strftime("%B %e at %H:%M") %>
          <% if post.parent_id %>
            as reply to <%= link_to post.parent.user.username, user_post_path(post.parent.user, post.parent) %>
          <% elsif post.community %>
            in <%= link_to post.community.name, community_path(post.community) %>
          <% else %>
            in Global 
          <% end %>
          <% if post.community %>
            <a href="#modalPostForm" class="pl-3" data-toggle="modal" data-id="<%= post.id %>" data-community="<%= post.community.id %>"><i class="fas fa-comment-dots"></i> Reply</a>
          <% else %>
            <a href="#modalPostForm" class="pl-3" data-toggle="modal" data-id="<%= post.id %>"><i class="fas fa-comment-dots"></i> Reply</a>
          <% end %>
          <a class="pl-3"><i class="fas fa-quote-right"></i> Repost</a>
          <%= link_to user_post_path(post.user, post), class: "pl-2" do %>
            View Post (<%= pluralize(post.replies.count, 'reply') %>)  
          <% end %>
          <% if post.user.id == current_user.id %>
            <%= link_to user_post_path(post.user, post), method: "delete", class: "pl-2", data: { confirm: 'Are you sure you want to delete this post?' } do %>
              <i class="fas fa-trash-alt"></i>
            <% end %>
          <% end %>
        </small>
      </div>
    </div>
  </div>
<%= render partial: "posts/reply_block", locals: {post: post.replies} %>
<% end %>

app/views/posts/edit.html.erb
<div class="container-lg container-body py-5 px-4">
<h2>Editing Post</h2>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>
</div>

app/views/posts/index.html.erb
<div class="container-lg container-body py-5 px-4">
  <div class="card-group">
    <%= render partial: "users/user_card", locals: {user: current_user} %>
      <div class="col-xl-8">
        <section class="my-4">
          <% if current_user %>
            <h2 class="float-left">All Posts</h2>
            <%= link_to "New Post", '#modalPostForm', class: "btn btn-sm btn-light-green float-right d-inline", data_toggle: "modal" %>
            <table class="table">
              <thead class="black white-text">
                <tr>
                  <th>Username</th>
                  <th>Body</th>
                  <th class="text-center">Actions</th>
                </tr>
              </thead>
              <tbody>
                <% @posts.each do |post| %>
                  <tr>
                    <td><%= link_to post.user.username, user_path(post.user) %></td>
                    <td><%= sanitize(post.body.truncate(180)) %></td>
                    <td>
                      <%= link_to 'Show', user_post_path(post.user, post) %>
                      <% if current_user && current_user.id == post.user.id %> 
                        <%# | <%= link_to 'Edit', user_edit_post_path(post.user, post) %> 
                        | <%= link_to 'Destroy', user_post_path(post.user, post), method: :delete, data: { confirm: 'Are you sure?' } %>
                      <% end %>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
            <div class="row float-right">
              <%= will_paginate @posts %>
            </div>
          <% end %>
        </section>
      </div>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="container-lg container-body py-5 px-4">
  <div class="card-group">
    <% if @post.community %>
      <%= render partial: "communities/sidebar", locals: {community: @post.community} %>
    <% else %>
      <%= render partial: "users/user_card", locals: {user: @post.user} %>
    <% end %>
    <div class="col-xl-8">
      <section class="my-4">
        <!-- Card header -->
        <div class="card-header border-0 font-weight-bold d-flex justify-content-between">
          <p class="mr-4 mb-0">
            Posted <%= @post.created_at.strftime("%B %e at %H:%M") %>
            <% if @post.community %>
              in <%= link_to @post.community.name, community_post_path(@post.community, @post) %>
            <% elsif @post.parent_id %>
              as reply to <%= link_to @post.parent.user.username, user_post_path(@post.parent.user, @post.parent) %>
            <% else %>
              in Global
            <% end %>
          </p>
          <ul class="list-unstyled list-inline mb-0">
            <li class="list-inline-item"><a href="" class="mr-3"><i class="fas fa-envelope mr-1"></i>Send message</a></li>
            <% if current_user && is_following?(@post.user) %>
              <li class="list-inline-item">
                <%= link_to user_follow_path(@post.user), method: "post" do %>
                  <i class="fas fa-at mr-1"></i>Unfollow
                <% end %>
              </li>
            <% elsif current_user && current_user.id == @post.user.id %>
            <% else %>
              <li class="list-inline-item">
                <%= link_to user_follow_path(@post.user), method: "post" do %>
                  <i class="fas fa-at mr-1"></i>Follow
                <% end %>
              </li>
            <% end %>
          </ul>
        </div>
          <div class="media mt-4 mb-3 px-1 text-md-left border-1">
    <div class="media-body ml-2 mt-1" style="width: 100%;">
    <% if @post.user.avatar.presence %>
      <%= image_tag @post.user.avatar.variant(resize_to_limit: [60, 60]), class: "card-img-60 d-flex rounded-circle mr-2 float-left" %>
    <% else %>
      <img class="card-img-40 d-flex mr-2 float-left" src="https://mdbootstrap.com/img/Photos/Avatars/img%20(8).jpg" alt="Generic placeholder image" height="40" width="40">
    <% end %>
      <h5 class="font-weight-bold mt-0 mb-0 text-muted float-left">
        <%= link_to @post.user.name, user_path(@post.user) %>
      </h5><br>
      <small class="text-muted d-block">@<%= link_to @post.user.username, user_path(@post.user) %></small>
      <p class="pt-3"><%= raw(@post.parsed_body) %></p>
            <% if @post.parent_id %>
              <div class="media mt-4 mb-4 px-2 pt-2 text-md-left border-1" style="background: #f9f9f9">
                <% if @post.parent.user.avatar.presence %>
                  <%= image_tag @post.parent.user.avatar.variant(resize_to_limit: [80, 80]), class: "card-img-80 d-flex rounded-circle mr-3" %>
                <% else %>
                  <img class="card-img-100 d-flex mr-3" src="https://mdbootstrap.com/img/Photos/Avatars/img%20(8).jpg" alt="Generic placeholder image">
                <% end %>
                <div class="media-body">
                  <h5 class="font-weight-bold mt-0 mb-0 text-muted">
                    <%= link_to @post.parent.user.name, user_post_path(@post.parent.user, @post.parent) %><small class="text-muted align-middle pl-2">@<%= link_to @post.parent.user.username, user_post_path(@post.parent.user, @post.parent) %></small>
                  </h5>
                  <p class="mt-2"><%= sanitize(@post.parent.parsed_body.truncate(300)) %></p>
                </div>
              </div>
            <% end %>
            <div class="row" style="background: #f9f9f9; padding-top: 5px; padding-bottom: 5px; margin-left: 1px; margin-right: 1px;">
              <small class="blue-grey-text pl-3">
                Posted <%= @post.created_at.strftime("%B %e at %H:%M") %>
                <% if @post.parent_id %>
                  as reply to <%= link_to @post.parent.user.username, user_post_path(@post.parent.user, @post.parent) %>
                <% elsif @post.community %>
                  in <%= link_to @post.community.name, community_path(@post.community) %>
                <% else %>
                  in Global 
                <% end %>
                <a href="#modalPostForm" class="pl-3" data-toggle="modal" data-id="<%= @post.id %>"><i class="fas fa-comment-dots"></i> Reply</a>
                <a class="pl-3"><i class="fas fa-quote-right"></i> Repost</a>
                <%= link_to user_post_path(@post.user, @post), class: "pl-2" do %>
                  View Post (<%= pluralize(@post.replies.count, 'reply') %>)  
                <% end %>
                <% if @post.user.id == current_user.id %>
                  <%= link_to user_post_path(@post.user, @post), class: "pl-2" do %>
                    <i class="fas fa-trash-alt"></i>
                  <% end %>
                <% end %>
              </small>
            </div>
          </div>
        </div>
        <%= render partial: "posts/reply_block", locals: {post: @post.replies.order(created_at: :desc)} %>
      </section>
    </div>
  </div>
</div>