config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'static#index'
  get '/about' => 'static#about'
  get '/contact' => 'static#contact'

  # User auth/sessions
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'
  get '/register' => 'users#new'
  match '/auth/:provider/callback', to: 'sessions#omni', via: %i[get post], as: 'omni'

  # Dashboard
  get '/users/dashboard' => 'users#dashboard'

  # Search
  get '/search' => 'search#index', as: 'search'
  get '/search?q=params[:query]' => 'search#results'

  resources :posts, only: %i[index create]

  namespace :private do
    resources :conversations
  end

  resources :users do
    get '/follow' => 'users#follow'
    get '/unfollow' => 'users#unfollow'
    resources :posts, except: %i[edit update]
  end

  resources :communities do
    get '/join' => 'communities#join'
    get '/leave' => 'communities#leave'
    get '/member-permissions' => 'communities#permissions'
    resources :posts, except: %i[edit update]
    resources :memberships, only: %i[edit update]
  end
end

app/models/community.rb
# frozen_string_literal: true

class Community < ApplicationRecord
  belongs_to :user, foreign_key: 'admin_id'

  has_many :posts, foreign_key: 'community_id'
  has_many :followers, class_name: 'Follow', foreign_key: 'following_community_id', dependent: :destroy
  has_many :community_memberships
  has_many :users, through: :community_memberships, source: :user

  has_one_attached :avatar
  has_one_attached :header_image

  validates :name, presence: true, uniqueness: true

  after_create :add_community_membership

  private

  def add_community_membership
    cm = CommunityMembership.create(user_id: admin_id, community_id: id, role: 2)
  end

  def self.is_member?
    community = communities.where(comm)
  end
end

app/controllers/communities_controller.rb
# frozen_string_literal: true

class CommunitiesController < ApplicationController
  include CommunitiesHelper
  before_action :set_community, only: [:show, :edit, :update, :destroy, :join, :leave, :permissions]

  # GET /communities
  def index
    @communities = Community.all
  end

  # GET /communities/1
  def show; end

  # GET /communities/new
  def new
    @community = Community.new
  end

  # GET /communities/1/edit
  def edit; end

  # POST /communities
  def create
    @community = Community.new(community_params)

    respond_to do |format|
      if @community.save
        format.html { redirect_to @community, notice: 'Community was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /communities/1
  def update
    respond_to do |format|
      if @community.update(community_params)
        format.html { redirect_to @community, notice: 'Community was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /communities/1
  def destroy
    @community.destroy
    respond_to do |format|
      format.html { redirect_to communities_url, notice: 'Community was successfully destroyed.' }
    end
  end

  def join
    membership = CommunityMembership.new(community_id: @community.id, user_id: current_user.id)
    if membership.save
      flash[:success] = "You are now a member of #{@community.name}!"
      redirect_to community_path(@community)
    else
      flash[:danger] = "Sorry, something went wrong. Please try again."
    end
  end

  def leave
    membership = current_user.community_memberships.find_by(community_id: @community.id)
    if membership.destroy
      flash[:success] = "You have successfully left #{@community.name}!"
      redirect_to community_path(@community)
    else
      flash[:danger] = "Sorry, something went wrong. Please try again."
      redirect_to community_path(@community)
    end
  end

  def permissions
    @memberships = CommunityMembership.where(community_id: @community.id)
    authorize! [:edit, :update], @memberships
  end

  private

  # Only allow a list of trusted parameters through.
  def community_params
    params.require(:community).permit(:name, :description, :post_id, :admin_id, :avatar, :header_image)
  end
end

app/helpers/communities_helper.rb
# frozen_string_literal: true

module CommunitiesHelper
  def is_community_admin?(user, community)
    c = user.community_memberships.find_by(community_id: community.id, role: 2)
    c ? true : false
  end

  def is_community_moderator?(user, community)
    c = user.community_memberships.where(community_id: community.id)
    c.role == 1
  end

  def is_community_member?(user, community)
    c = user.community_memberships.find_by(community_id: community.id)
    c ? true : false
  end

  def community_role(user, community)
    if user.community_memberships.find_by(community_id: community.id, role: 'admin')
      'Admin'
    elsif user.community_memberships.find_by(community_id: community.id, role: 'moderator')
      'Moderator'
    elsif user.community_memberships.find_by(community_id: community.id, role: 'member')
      'Member'
    end
  end

  def get_admins(community)
    admins = CommunityMembership.where(community_id: community.id, role: 2)

    admins.collect do |admin|
      User.find(admin.user_id)
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_community
    @community = if params[:community_id]
                   Community.find(params[:community_id])
                 else
                   Community.find(params[:id])
                 end
  end
end

app/views/communities/_form.html.erb
<%= form_with model: @community, local: true do |f| %>
<div class="row">
  <div class="col-md-6">
    <div class="form-group mx-auto text-center">
      <% if community.avatar.presence %>
        <%= image_tag community.avatar.variant(resize_to_limit: [100, 100]), class: "mb-3 mx-auto" %>
      <% end %>
      <div class="row mx-auto">
        <%= label_tag :avatar, "Avatar", class: "mt-4 mx-auto" %>
        <%= f.file_field :avatar, class: "form-control-file mx-auto mb-4" %>
      </div>
    </div>
  </div>
  <div class="col-md-6">
    <div class="form-group mx-auto text-center">
      <% if community.header_image.presence %>
        <%= image_tag community.header_image.variant(resize_to_limit: [200, 200]), class: "mb-3 mx-auto" %>
      <% end %>
      <div class="row mx-auto">
        <%= label_tag :header_image, "Header Image", class: "mt-4 mx-auto" %>
        <%= f.file_field :header_image, class: "form-control-file mx-auto mb-4" %>
      </div>
    </div>
  </div>
</div>

  <div class="form-field">
    <%= f.label :name, data_toggle: "tooltip", data_placement:"top", title: "Community name can't be changed." %>
    <%= f.text_field :name, class: "form-control form-control-lg", disabled: true, data_toggle: "tooltip", data_placement:"top", title: "Community name can't be changed." %>
  </div>

  <div class="form-field mt-3">
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control form-control-lg", rows: "7" %>
  </div>

  <div class="form-field float-right mt-2">
    <%= f.submit "Submit", :class => "btn btn-primary" %>
      <% if community %>
        <%= f.submit "Delete Community", :class => "btn btn-danger mx-2", data: { confirm: 'Are you sure? This will delete your account and ALL associated data!' } %>
      <% end %>
  </div>
<% end %>

app/views/communities/_new_form.erb
<%= form_with model: community, local: true do |f| %>
<div class="row">
  <div class="col-md-6">
    <div class="form-group mx-auto text-center">
      <div class="row mx-auto">
        <%= label_tag :avatar, "Avatar", class: "mt-4 mx-auto" %>
        <%= f.file_field :avatar, class: "form-control-file mx-auto mb-4" %>
      </div>
    </div>
  </div>
  <div class="col-md-6">
    <div class="form-group mx-auto text-center">
      <div class="row mx-auto">
        <%= label_tag :header_image, "Header Image", class: "mt-4 mx-auto" %>
        <%= f.file_field :header_image, class: "form-control-file mx-auto mb-4" %>
      </div>
    </div>
  </div>
</div>

  <div class="form-field">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control form-control-lg" %>
  </div>

  <div class="form-field mt-3">
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control form-control-lg", rows: "7" %>
  </div>

  <div class="form-field float-right mt-2">
    <%= f.submit "Submit", :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/communities/_sidebar.erb
<div class="col-xl-4">
  <div class="card card-cascade wider reverse">
    <!-- Card image -->
    <div class="view view-cascade overlay">
      <% if community.header_image.presence %>
        <%= image_tag community.header_image, class: "card-img-top header-image" %>
      <% else %>
        <img class="card-img-top" src="https://mdbootstrap.com/img/Photos/Slides/img%20(70).jpg" alt="Card image cap">
      <% end %>
      <a href="#!">
        <div class="mask rgba-white-slight"></div>
      </a>
    </div>
    <div class="card-avatar mx-auto d-block">
      <% if community.avatar.presence %>
        <%= image_tag community.avatar.variant(resize_to_limit: [120, 120]), class: "rounded-circle" %>
      <% else %>
        <img class="card-img-100 d-flex" src="https://mdbootstrap.com/img/Photos/Avatars/img%20(8).jpg" alt="Generic placeholder image">
      <% end %>
    </div>
    <!-- Card content -->
    <div class="card-body card-body-cascade text-center">
      <!-- Title -->
      <h4 class="card-title"><strong><%= community.name %></strong></h4>
      <!-- Subtitle -->
      <h6 class="font-weight-bold indigo-text pb-1 pt-0 mt-0">About</h6>
      <!-- Text -->
      <p class="card-text"><%= community.description %></p>

      <p>
      <% if is_community_member?(current_user, community) %>
        <%= link_to "Leave", community_leave_path(community), class: "btn btn-danger btn-sm btn-block" %>
      <% else%>
        <%= link_to "Join", community_join_path(community), class: "btn btn-primary btn-sm btn-block" %>
      <% end %>
      </p>

      <p>
        <strong>Admin(s)</strong><br>
          <% get_admins(community).each do |admin| %>
            <%= link_to admin.username, user_path(admin) %>
          <% end %>

          <br>
      
        <% if is_community_admin?(current_user, community) %>
          <%= link_to 'User Permissions', community_member_permissions_path(community) %> |
          <%= link_to 'Edit', edit_community_path(community) %> |
          <%= link_to 'Back', communities_path %>
        <% end %>
      </p>
      <!-- Linkedin -->
      <a class="px-2 fa-lg li-ic"><i class="fab fa-linkedin-in"></i></a>
      <!-- Twitter -->
      <a class="px-2 fa-lg tw-ic"><i class="fab fa-twitter"></i></a>
      <!-- Dribbble -->
      <a class="px-2 fa-lg fb-ic"><i class="fab fa-facebook-f"></i></a>
    </div>
  </div>
  <div class="card card-cascade wider mt-3">
    <!-- Card image -->
    <div class="view view-cascade gradient-card-header peach-gradient">
      <!-- Title -->
      <h2 class="card-header-title my-4 white-text mx-auto text-center"><strong><%= community.users.length %></strong> <small class="mb-0">Members</small></h2>
      <!-- Text -->
    </div>
  </div>
</div>

app/views/communities/edit.html.erb
<div class="container-lg container-body py-5 px-4">
  <div class="card-group">
    <%= render partial: "communities/sidebar", locals: {community: @community} %>
      <div class="col-xl-8">
        <section class="my-4">
          <h2>Editing <%= @community.name %></h2>

          <%= render 'form', community: @community %>

        </section>
      </div>
    </div>
  </div>
</div>

app/views/communities/index.html.erb
<div class="container-lg container-body py-5 px-4">
  <div class="card-group">
    <%= render partial: "users/user_card", locals: {user: current_user} %>
      <div class="col-xl-8">
        <section class="my-4">
          <% if current_user %>
            <h2 class="float-left">My Communities</h2>
            <%= link_to "Create Community", new_community_path, class: "btn btn-sm btn-light-green float-right d-inline" %>
            <table class="table">
              <thead class="black white-text">
                <tr>
                  <th>Name</th>
                  <th>Description</th>
                  <th>Actions</th>
                </tr>
              </thead>

              <tbody>
                <% current_user.memberships.each do |community| %>
                  <tr>
                    <td><%= link_to community.name, community_path(community) %></td>
                    <td><%= community.description %></td>
                    <td>
                      <%= link_to 'View', community %> 
                      <% if is_community_admin?(current_user, community) %>
                        | <%= link_to 'Edit', edit_community_path(community) %> | 
                        <%= link_to 'Destroy', community, method: :delete, data: { confirm: 'Are you sure?' } %>
                      <% end %>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          <% end %>


          <h2 class="pt-5">All Communities</h2>
          <table class="table">
            <thead class="black white-text">
              <tr>
                <th>Name</th>
                <th>Description</th>
                <th>Actions</th>
              </tr>
            </thead>

            <tbody>
              <% @communities.each do |community| %>
                <tr>
                  <td><%= link_to community.name, community_path(community) %></td>
                  <td><%= community.description %></td>
                  <td>
                    <%= link_to 'View', community %> 
                    <% if is_community_admin?(current_user, community) %>
                      | <%= link_to 'Edit', edit_community_path(community) %> | 
                      <%= link_to 'Destroy', community, method: :delete, data: { confirm: 'Are you sure?' } %>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </section>
      </div>
    </div>
  </div>
</div>

app/views/communities/new.html.erb
<div class="container-lg container-body py-5 px-4">
  <div class="card-group">
    <%= render partial: "users/user_card", locals: {user: current_user} %>
      <div class="col-xl-8">
        <section class="my-4">
          <h2>Create a Community</h2>

          <%= render "new_form", community: @community %>

        </section>
      </div>
    </div>
  </div>
</div>

app/views/communities/permissions.erb
<div class="container-lg container-body py-5 px-4">
<% flash.each do |name, msg| %>
  <%= content_tag :div, class: "note note-#{name} fade show mb-4" do %>
    <%= msg %>
  <% end %>  
<% end %>
  <div class="card-group">
    <%= render partial: "communities/sidebar", locals: {community: @community} %>
      <div class="col-xl-8">
        <section class="my-4">
          <% if current_user %>
            <h2>Users</h2>
            <table class="table">
              <thead class="black white-text">
                <tr>
                  <th>Username</th>
                  <th>Name</th>
                  <th>E-mail</th>
                  <th>Role</th>
                  <th class="text-center">Actions</th>
                </tr>
              </thead>

              <tbody>
                <% @memberships.each do |membership| %>
                  <tr>
                    <td><%= link_to membership.user.username, user_path(membership.user) %></td>
                    <td><%= link_to membership.user.name, user_path(membership.user) %></td>
                    <td><%= membership.user.email %></td>
                    <td>
                      <%= form_with url: community_membership_path(id: membership.id), method: "patch" do |f| %>
                        <select name="community_membership[role]">
                            <option value="<%= community_role(membership.user, @community).downcase %>"><%= community_role(membership.user, @community) %></option>
                            <option value="member">Member</option>
                            <option value="moderator">Moderator</option>
                            <option value="admin">Admin</option>
                        </select><br>
                        <%= f.submit "Change", :class => "btn btn-primary btn-sm" %>
                      <% end %>
                    </td>
                    <td class="text-center">
                      <%= link_to 'View Profile', membership.user %> 
                      <% if is_admin?(current_user) %>
                        | <%= link_to 'Edit', edit_user_path(membership.user) %> 
                      <% end %>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
            <div class="row float-right">
              
            </div>
          <% end %>
        </section>
      </div>
    </div>
  </div>
</div>

app/views/communities/show.html.erb
<div class="container-lg container-body py-5 px-4">
  <% flash.each do |name, msg| %>
  <%= content_tag :div, class: "note note-#{name} fade show mb-4" do %>
    <%= msg %>
  <% end %>  
<% end %>
  <div class="card-group">
    <%= render partial: "communities/sidebar", locals: {community: @community} %>
      <div class="col-xl-8">
        <section class="my-4">
          <!-- Card header -->
          <div class="card-header border-0 font-weight-bold d-flex justify-content-between">
            <p class="mr-4 mb-0">Activity Feed </p>
            <ul class="list-unstyled list-inline mb-0">
              
            </ul>
          </div>
        <%= render partial: "posts/post_block", locals: {post: @community.posts} %>
      </div>
    </div>
  </div>
</div>