config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'static#index'
  get '/about' => 'static#about'
  get '/contact' => 'static#contact'

  # User auth/sessions
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'
  get '/register' => 'users#new'
  match '/auth/:provider/callback', to: 'sessions#omni', via: %i[get post], as: 'omni'

  # Dashboard
  get '/users/dashboard' => 'users#dashboard'

  # Search
  get '/search' => 'search#index', as: 'search'
  get '/search?q=params[:query]' => 'search#results'

  resources :posts, only: %i[index create]

  namespace :private do
    resources :conversations
  end

  resources :users do
    get '/follow' => 'users#follow'
    get '/unfollow' => 'users#unfollow'
    resources :posts, except: %i[edit update]
  end

  resources :communities do
    get '/join' => 'communities#join'
    get '/leave' => 'communities#leave'
    get '/member-permissions' => 'communities#permissions'
    resources :posts, except: %i[edit update]
    resources :memberships, only: %i[edit update]
  end
end

app/views/layouts/_navbar.erb
<!--Navbar -->
<nav class="mb-0 navbar navbar-expand-lg navbar-dark blue-gradient">
  <div class="container">
    <% if current_user %>
      <a class="navbar-brand" href="/users/dashboard">Speek</a>
    <% else %>
      <a class="navbar-brand" href="/">Speek</a>
    <% end %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent-333"
      aria-controls="navbarSupportedContent-333" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse text-center" id="navbarSupportedContent-333">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <form class="form-inline">
            <div class="md-form my-0">
              <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search" name="search_name">

            </div>
          </form>
        </li>
      </ul>
      <ul class="navbar-nav ml-auto nav-flex-icons">
        <li class="nav-item">
          <a class="nav-link waves-effect waves-light" href="/communities">
            <i class="fas fa-home"></i>
            Communities
          </a>
        </li>
        <% if current_user %>
          <li class="nav-item">
            <a class="nav-link waves-effect waves-light" data-toggle="modal" data-target="#modalPostForm">
              <i class="fas fa-plus"></i>
              New Post
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect waves-light">1
              <i class="fas fa-envelope"></i>
            </a>
          </li>
          <% if current_user.avatar.presence %>
            <li class="nav-item avatar dropdown">
              <a class="nav-link" id="navbarDropdownMenuLink-333" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">
                <%= image_tag current_user.avatar.variant(resize_to_limit: [25, 25]), class: "rounded-circle z-depth-0" %>
              </a>
            <% else %>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink-333" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">
                  <i class="fas fa-user"></i>
                  @<%= current_user.username %>
                </a>
              <% end %>
              <div class="dropdown-menu dropdown-menu-lg-right dropdown-secondary"
            aria-labelledby="navbarDropdownMenuLink-333">
                <%= link_to "Your Profile", user_path(current_user), class: "dropdown-item" %>
                <%= link_to "Edit Profile", edit_user_path(current_user), class: "dropdown-item" %>
                <%= link_to "Logout", logout_path, method: "delete", class: "dropdown-item" %>
              </div>
            </li>
          <% else %>
            <li class="nav-item">
              <a class="nav-link waves-effect waves-light" data-toggle="modal" data-target="#modalLoginForm">
                <i class="fas fa-user"></i>Login
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link waves-effect waves-light" href="/register">
                <i class="fas fa-user"></i>Register
              </a>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
  <!--/.Navbar -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Speek</title>
    <%= csrf_meta_tags %> 
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag 'application', media: "all", 'data-turbolinks-track' => true %>
    <%= favicon_link_tag 'favicon.ico' %>
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
    <!-- Google Fonts -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap">
    <!-- Bootstrap core CSS -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/css/bootstrap.min.css" rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.19.1/css/mdb.min.css" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>
  <body style="background: #f5f5f5;">
    <%= render "layouts/navbar" %>

    <%= render "sessions/login_modal" %>
    <% if current_user%>
      <%= render "posts/new_post_modal" %>
    <% end %>

    <% flash.each do |name, msg| %>
      <div class="container pt-2" style="background: #fff">
        <% if @user && @user.errors.full_messages.any? %>
          <% @user.errors.full_messages.each do |error_message| %>
              <div class="note note-warning fade show mt-2">
                <%= error_message %>
              </div>
          <% end %>
        <% end %>
        <% if @community && @community.errors.full_messages.any? %>
          <% @community.errors.full_messages.each do |error_message| %>
              <div class="note note-warning fade show mt-2">
                <%= error_message %>
              </div>
          <% end %>
        <% end %>
      </div> 
    <% end %> 

  <%= yield %>
<div class="container d-block d-lg-none" style="position relative">
  <a class="btn-floating btn-lg btn-deep-purple btn-circle d-block d-lg-none" style="position: fixed; bottom: 20px; right: 20px;" data-toggle="modal" data-target="#modalPostForm"><i class="fas fa-plus white-text"></i></a>
</div>



<script type="text/javascript">
$('#modalPostForm').on('show.bs.modal', function(e) {
    var postId = $(e.relatedTarget).data('id');
    $(e.currentTarget).find('input[name="post[parent_id]"]').val(postId);
});

$('#modalPostForm').on('show.bs.modal', function(e) {
    var communityId = $(e.relatedTarget).data('community');
    $(e.currentTarget).find('select[name="post[community_id]"]').val(communityId);
});
</script>
  </body>
</html>